// --- Mock Data & i18n ---
        const translations = {
            en: {
                welcomeTitle: "Welcome to DropNow",
                welcomeSubtitle: "Print your memories beautifully with DropNow.",
                continue: "Continue",
                permissionsTitle: "Permissions",
                permissionsSub: "DropNow Air and Pro need a few permissions to deliver a seamless printing experience.",
                bluetoothTitle: "Bluetooth",
                bluetoothDesc: "To connect and print to your device.",
                cameraTitle: "Camera",
                cameraDesc: "To take photos directly in the app.",
                photoTitle: "Photos",
                photoDesc: "To select and print your existing memories.",
                allowAll: "Allow Access",
                prefsTitle: "Preferences",
                prefsSub: "Customize your experience. You can always change these later.",
                leftHanded: "Left-Handed Mode",
                leftHandedDesc: "Optimizes layout for left-handed use.",
                theme: "Theme",
                system: "System",
                light: "Light",
                dark: "Dark",
                largerText: "Larger Text",
                highContrast: "High Contrast",
                crop: "Crop",
                zoom: "Zoom",
                resetCrop: "Reset",
                dragPhotoHint: "Drag photo to crop, use zoom to scale.",
                start: "Get Started",
                home: "Home",
                works: "My Works",
                settings: "Settings",
                connectPrinter: "Connect your DropNow Air or Pro",
                printerDisconnected: "DropNow printer disconnected",
                readyToPrint: "DropNow ready to print",
                takePhoto: "Take Photo",
                chooseLibrary: "Choose from Library",
                collagePrint: "Collage Print",
                cancel: "Cancel",
                nearbyPrinters: "Nearby DropNow Printers",
                scanning: "Scanning for printers...",
                connect: "Connect",
                connected: "Connected",
                troubleshooting: "Troubleshooting",
                howToConnect: "Turn on your DropNow Air or DropNow Pro and make sure Bluetooth is enabled on your device.",
                libraryTitle: "Select Photo",
                next: "Next",
                reviewTitle: "Review",
                directPrint: "Direct Print",
                customizePrint: "Customize",
                editorTitle: "Edit Photo",
                brightness: "Brightness",
                contrast: "Contrast",
                frame: "Frame",
                noFrame: "None",
                classicFrame: "Classic",
                brandFrame: "DropNow",
                thinFrame: "Thin",
                print: "Print",
                collageTitle: "Collage",
                printing: "Printing...",
                printSuccess: "Print Successful!",
                printAgain: "Print Again",
                customizeAfterPrint: "Customize Print",
                backHome: "Back to Home",
                historyEmpty: "No prints yet.",
                delete: "Delete",
                duplicate: "Duplicate",
                share: "Share",
                language: "Language",
                accessibility: "Accessibility",
                deviceInfo: "Device Info",
                firmware: "Firmware Version",
                reconnect: "Reconnect Printer",
                help: "Help & Support",
                privacy: "Privacy Policy",
                version: "App Version",
                aspectRatio: "Aspect Ratio",
                selectLayout: "Select Layout",
                cameraActive: "Camera Active",
                generating: "Generating...",
                cameraPermissionHint: "Allow camera access to take a real photo with your device.",
                cameraPermissionError: "Camera access failed. Check browser permission and device availability.",
                retryCamera: "Retry Camera",
                chooseLocalPhotos: "Choose Local Photos",
                noLocalPhotos: "No local photos selected yet. Choose images from your computer.",
                cameraNotReady: "Camera is not ready yet.",
                usePhoto: "Use Photo",
                choosePhotoForSlot: "Choose Photo",
                chooseCapturedPhoto: "Choose Taken Photo",
                useDirectly: "Use Directly",
                editBeforeUse: "Edit First",
                retakePhoto: "Retake Photo",
                fillCollageSlots: "Please fill every visible collage slot before printing.",
                noTakenPhotos: "No taken photos yet.",
                addPhoto: "+",
                replacePhoto: "Replace Photo",
                removePhoto: "Remove Photo",
                editCurrentPhoto: "Edit Current Photo",
                chooseAnotherPhoto: "Choose Another Photo",
                flipCamera: "Flip Camera",
                cameraSwitchUnavailable: "Camera switch is unavailable on this device.",
                chooseAnotherTakenPhoto: "Choose Another Taken Photo"
            },
            zh: {
                flipCamera: "\u5207\u6362\u955c\u5934",
                cameraSwitchUnavailable: "\u5f53\u524d\u8bbe\u5907\u65e0\u6cd5\u5207\u6362\u955c\u5934\u3002",
                welcomeTitle: "欢迎使用 DropNow",
                welcomeSubtitle: "使用 DropNow，将回忆快速打印出来。",
                continue: "继续",
                permissionsTitle: "权限设置",
                permissionsSub: "为了让 DropNow Air / Pro 提供顺畅的打印体验，需要以下权限。",
                bluetoothTitle: "蓝牙",
                bluetoothDesc: "用于连接打印机并进行打印。",
                cameraTitle: "相机",
                cameraDesc: "用于直接在应用内拍照。",
                photoTitle: "照片",
                photoDesc: "用于选择并打印您现有的回忆。",
                allowAll: "允许访问",
                prefsTitle: "偏好设置",
                prefsSub: "定制您的体验。您可以随时在设置中更改。",
                leftHanded: "左手模式",
                leftHandedDesc: "为左手使用优化布局。",
                theme: "外观",
                system: "跟随系统",
                light: "浅色",
                dark: "深色",
                largerText: "大号字体",
                highContrast: "高对比度",
                crop: "裁剪",
                zoom: "缩放",
                resetCrop: "重置",
                dragPhotoHint: "拖动照片调整裁剪区域，再用缩放控制大小。",
                start: "开始使用",
                home: "首页",
                works: "我的作品",
                settings: "设置",
                connectPrinter: "连接你的 DropNow Air 或 Pro",
                printerDisconnected: "DropNow 打印机未连接",
                readyToPrint: "DropNow 已就绪，可开始打印",
                takePhoto: "拍照",
                chooseLibrary: "从相册选择",
                collagePrint: "拼图打印",
                cancel: "取消",
                nearbyPrinters: "附近的 DropNow 打印机",
                scanning: "正在扫描打印机...",
                connect: "连接",
                connected: "已连接",
                troubleshooting: "故障排除",
                howToConnect: "请先开启你的 DropNow Air 或 DropNow Pro，并确认设备蓝牙已打开。",
                libraryTitle: "选择照片",
                next: "下一步",
                reviewTitle: "预览",
                directPrint: "直接打印",
                customizePrint: "个性化编辑",
                editorTitle: "编辑照片",
                brightness: "亮度",
                contrast: "对比度",
                frame: "边框",
                noFrame: "无边框",
                classicFrame: "经典拍立得",
                brandFrame: "DropNow 品牌款",
                thinFrame: "细边框",
                print: "打印",
                collageTitle: "拼图",
                printing: "正在打印...",
                printSuccess: "打印成功！",
                printAgain: "再打一张",
                customizeAfterPrint: "编辑后打印",
                backHome: "返回首页",
                historyEmpty: "暂无打印记录。",
                delete: "删除",
                duplicate: "复制",
                share: "分享",
                language: "语言",
                accessibility: "辅助功能",
                deviceInfo: "设备信息",
                firmware: "固件版本",
                reconnect: "重新连接打印机",
                help: "帮助与支持",
                privacy: "隐私政策",
                version: "应用版本",
                aspectRatio: "比例",
                selectLayout: "选择布局",
                cameraActive: "相机已开启",
                generating: "正在合成...",
                cameraPermissionHint: "允许相机权限后，即可直接使用电脑摄像头拍照。",
                cameraPermissionError: "摄像头调用失败，请检查浏览器权限或设备是否可用。",
                retryCamera: "重试相机",
                chooseLocalPhotos: "选择本地照片",
                noLocalPhotos: "还没有选择本地照片，请从电脑中选择图片。",
                cameraNotReady: "摄像头尚未准备好。",
                usePhoto: "使用照片",
                choosePhotoForSlot: "选择照片",
                chooseCapturedPhoto: "选择已拍照片",
                useDirectly: "直接使用",
                editBeforeUse: "先编辑",
                retakePhoto: "重新拍照",
                fillCollageSlots: "请先填满当前可见的拼图格子后再打印。",
                noTakenPhotos: "还没有拍过的照片。",
                addPhoto: "+",
                replacePhoto: "替换照片",
                removePhoto: "删除照片",
                editCurrentPhoto: "编辑当前照片",
                chooseAnotherPhoto: "重新选照片",
                chooseAnotherTakenPhoto: "重新选已拍照片"
            }
        };

        const MOCK_PRINTERS = [
            { id: 'p1', name: 'DropNow Air' },
            { id: 'p2', name: 'DropNow Pro' }
        ];

        const MOCK_PHOTOS = [];
